issues:
  exclude-use-default: false
linters:
  disable-all: true
  enable:
    - revive
linters-settings:
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        arguments:
          - maxLitCount: "1"
            allowStrs: '""'
            allowInts: "0,1"
      - name: argument-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
